services:
  postgres:
    container_name: postgres
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fullcontact
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5433:5432"

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "80:80"
    restart: always
    volumes:
      - staticvolume:/usr/share/nginx/html/static
    depends_on:
      backend:
        condition: service_healthy

    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost/favicon.ico > /dev/null || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s

    
      
  backend:
    container_name: backend
    build:
      context: ./fc
    volumes:
      - staticvolume:/app/static
      - ./fc/fcapi/migrations:/app/fcapi/migrations  # Mount host directory to container path
      
      
    ports:
      - "8000:8000"

    restart: always
    depends_on:
      postgres:
        condition: service_healthy


    healthcheck:
      test: [ "CMD", "curl", "-fsS", "http://localhost:8000/api/companies/" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  pgdata:
  staticvolume:


